auth-server: http://sso-login:10080/auth
server:
  port: 10081
  servlet:
    context-path: /client1
security:
  oauth2:
    client:
      client-id: client1
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
      registered-redirect-uri: http://sso-taobao:10081/client1
    resource:
      user-info-uri: ${auth-server}/token/user
#      token-info-uri: ${auth-server}/oauth/check_token

logging:
  level:
    com.example.sso.auth.client: debug
