server:
  port: 10080
cas:
  server:
    host:
      url: http://localhost:8080/cas
      login_url: ${cas.server.host.url}/login
      logout_url: ${cas.server.host.url}/logout?service=${app.server.host.url}
app:
  server:
    host:
      url: http://sso-taobao:28808
  login:
    url: /login
  logout:
    url: /logout
