server:
  port: 10080
  servlet:
    context-path: /auth
spring:
  session:
    store-type: redis
    # never timeout
    timeout: -1
    redis:
      namespace: saas:auth:spring:session
      flush-mode: on_save
  application:
    name: sso-auth-server
  redis:
    database: 0
    host: 10.3.0.79
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/saas_sso?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: a
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
logging:
#  level:
#    com.example.sso.auth.client: debug
#    org.springframework.security: debug
  config: classpath:log4j2.xml

# 允许跨域的地址
allow:
  origins: http://sso-taobao:10081,http://sso-login:10080/auth,http://localhost:8080,http://localhost:3001,http://localhost:3000,http://sso-tmall:10082
oauth2:
  code:
    redis:
      prefix: saas:auth:oauth2:code