###  前端根据密码方式登录 获取 token
POST {{host-sso}}:{{port}}/auth/oauth/token?grant_type=password&username ={{username}}&password={{password}}&scope={{scope}}
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Basic Y2xpZW50MToxMjM0NTY=

> {% client.global.set("token", response.body.access_token); %}
###

### 请求 client1

GET {{host-sso}}:{{port}}/client1/user
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
###

### 请求 client1 info
GET {{host-sso}}:{{port}}/client1/info
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
###

###  client1 请求 client2 info
GET {{host-sso}}:{{port}}/client1/info-client2
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}
###



### 请求 client2

GET {{host-sso}}:{{port}}/client2/index.html
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: Bearer {{token}}

###

### 退出登录

DELETE {{host-sso}}:{{port}}/auth/token/logout
Content-Type: application/json
Accept: application/json
Cache-Control: no-cache
Authorization: {{token}}

> {% client.global.clearAll() %}
###




